seed: 3407
use_wandb: False  # enable for reporting metrics to wandb
wandb_project: project_name  # enter your project name here
wandb_entity: project_entity  # enter your entity here
# dataset configuration
chekpoint_folder: "cifar_checkpoints"
checkpoint_freq: 1
grad_source: 'sbg'

# loss and optimization configuration
pag_coeff: 1.5
num_grads_per_image: 10

# architecture
arch: rn18


# training configuration
epochs: 100
batch_size: 64
weight_decay: 0.0001
lr: 0.01
momentum: 0.9